api_platform:
    title: Atelier Vélo API
    description: 'API pour atelier vélo participatif '
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
             JWT:
                name: Authorization
                type: header
        versions: [3]
    formats:
        json: ['application/json']
