# easy_admin:
#     entities:
#         Bicycle:
#             # class: App\Entity\Bicycle
#             list:
#                 fields:
#                     - { property: 'disponibility', type: 'boolean' }
#                     - { property: 'image', type: 'image' }