name: atelier
recipe: symfony
config:
  webroot: public
services:
  database:
    type: mysql
    portforward: 3307
    creds: 
      user: rita
      password: admin
      database: atelier
  node:
    type: node:14
    build:
      - yarn install
      # - npm install 
tooling:
  yarn: 
    service: node
  node:
    service: node
  npm:
    # service: node 